/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws FileNotFoundException {
        File file = new File("mainProject/src/main/resources/file.txt");
        Scanner sc = new Scanner(file);
        String str = sc.nextLine();
        String str2 = sc.nextLine();
        Substring substring = new Substring();
        substring.findSubstring(str,str2);
    }
}
