/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import java.util.Random;
import static org.junit.Assert.assertEquals;

public class AppTest {
    Substring substring = new Substring();

    public String generateString(String characters, int length) {
        char[] text = new char[length];
        Random rng = new Random();
        for (int i = 0; i < length; i++) text[i] = characters.charAt(rng.nextInt(characters.length()));
        return new String(text);
    }

    @Test
    public void testSimple() {
        substring.findSubstring(generateString("abcd1234", 10), generateString("abcd1234", 10));
    }

    @Test
    public void testStressTestOne() {
        for (int i = 0; i < 1000; i++)
            substring.findSubstring(generateString("abcd", 10), generateString("abcd", 10));
    }

    @Test
    public void testStressTestTwo() {
        substring.findSubstring(generateString("abcd", 5000), generateString("abcd", 5000));
    }

    @Test
    public void testStressTestThree() {
        substring.findSubstring(generateString("abcd", 8000), generateString("abcd", 10000));
    }

    @Test
    public void testBlackBox() {
        assertEquals("abc", substring.findSubstring("dsjabcsdhd", "uaaddciabcds"));
    }

    @Test
    public void testBlackBoxTwo() {
        assertEquals("", substring.findSubstring("", "uaaddciabcds"));
    }
}
